### PR TITLE
Convert to Python3

### PR DESCRIPTION
**Pull request by ralic**
using : find . -name '*.py' | xargs 2to3 -w

### CODE REVIEW

**Comment by emo-eth** [comment]
This package is already compatible with Python 3 (and developed in Python 3.5) - these changes just casts the `dict.items()` generators as lists. Are you having problems running it on your system? If so, you might look into updating your Python install.

**Comment by JacobAMason** [comment]
@jameswenzel This guy is running a bot. Check his recent PRs (and then report him to GitHub).

**Comment by emo-eth** [comment]
@JacobAMason Figured it might be something like that, it's just such banal/benign spam... thanks for the heads up.

**Comment by ralic** [comment]
Sorry, I have stopped the crawling for pushing updates. The porting script may create confusion for packages that is already python3 compatible.

**Pull request closed without merging**
